sudo: required

language: python

cache: pip

python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install flac lame vorbis-tools faac

install:
  - pip install -r dev_requirements.txt

script:
  - py.test tests/test_flacthis.py
